### ISSUE TITLE
opus_buildtype.cmake is missing in opus 1.3.1 tar

### ISSUE THREAD

**Issue by mnpaunov** [xiph/opus#129] opened 2019-04-23 16:35 UTC
@xnorpx
In the newest release (opus-1.3.1) the CMakeLists.txt is looking for "opus_buildtype.cmake" which is missing from the distributed tar, but is present in the git repo.

**Comment by xnorpx** [comment] 2019-04-23 20:51
Thanks @mnpaunov I added a pull request for @jmvalin to approve.

**Comment by willson-chen** [comment] 2019-08-15 08:02
I reproduced it by type `cmake .`. The error information as follow:
```
CMake Error at CMakeLists.txt:19 (include):
  include could not find load file:

    opus_buildtype.cmake
```
And no makefile was generated.

**Comment by rillian** [comment] 2019-08-15 15:20
Right. I merged the patch in 86e5f5ea56, but didn't mark this issue as resolved. This is just waiting for a new release.

Sounds like we need to add a cmake build to `make distcheck`!

**Closed** 2019-08-15 15:20 UTC

**Comment by willson-chen** [comment] 2019-08-16 01:11
@rillian Wow, nice to see you here

**Comment by aberaud** [comment] 2023-01-12 21:55
No release since 2019 and the problem is still there :)

**Comment by JarvisChu** [comment] 2023-01-18 08:34
I fixed this problem by copy the  "opus_buildtype.cmake"  file from https://github.com/bincrafters/conan-opus/blob/stable/1.3.1/opus_buildtype.cmake

**Comment by markand** [comment] 2023-03-10 11:56
Any chance we get a new release just for that fix? e.g. 1.3.2. This breaks Windows builds.
