### ISSUE TITLE
Compile fails when ARCH_HAVE_SSE

### ISSUE THREAD

**Issue by snorkellingcactus** [xiph/opus#28] opened 2017-01-26 02:17 UTC
Hi. I am on a sse-only machine. I noticed that in test_unit_rotation.c and test_unit_mathops.c some files that could use celt_inner_prod_sse by macro expansion of celt_inner_prod like pitch.c and vq.c are included before pitch_sse.c resulting in errors.

I only changed the order of the includes and it compiles fine. I'm not sure but also could be needed the inclusion of vq.c after pitch.c.

Maybe unrelated, but i don't know much about c/c++ but i like to learn and i wonder why the compiler could mark a macro function as an implicit declaration of that function. ¿do you know?. It happened to me on pitch_sse.h:115.

I think it's not needed but i will atach a build log and a little patch.

Thanks.

**Comment by snorkellingcactus** [comment] 2017-01-26 02:19
`
diff --git a/celt/tests/test_unit_mathops.c b/tmp/opus/test_unit_mathops.c
index fd3319d..8049f2a 100644
--- a/celt/tests/test_unit_mathops.c
+++ b/tmp/opus/test_unit_mathops.c
@@ -45,11 +45,6 @@
 #include "bands.c"
 #include "quant_bands.c"
 #include "laplace.c"
-#include "vq.c"
-#include "cwrs.c"
-#include "pitch.c"
-#include "celt_lpc.c"
-#include "celt.c"
 
 #if defined(OPUS_X86_MAY_HAVE_SSE) || defined(OPUS_X86_MAY_HAVE_SSE2) || defined(OPUS_X86_MAY_HAVE_SSE4_1)
 # if defined(OPUS_X86_MAY_HAVE_SSE)
@@ -83,6 +78,12 @@
 #define WORD "%f"
 #endif
 
+#include "pitch.c"     // Note: It could use celt_inner_prod_sse
+#include "celt_lpc.c"
+#include "celt.c"
+#include "vq.c"         // Note: It could use celt_inner_prod_sse
+#include "cwrs.c"
+
 int ret = 0;
 
 void testdiv(void)
diff --git a/celt/tests/test_unit_rotation.c b/tmp/opus/test_unit_rotation.c
index 1080c20..a157b72 100644
--- a/celt/tests/test_unit_rotation.c
+++ b/tmp/opus/test_unit_rotation.c
@@ -37,17 +37,12 @@
 
 #include <stdio.h>
 #include <stdlib.h>
-#include "vq.c"
 #include "cwrs.c"
 #include "entcode.c"
 #include "entenc.c"
 #include "entdec.c"
 #include "mathops.c"
 #include "bands.h"
-#include "pitch.c"
-#include "celt_lpc.c"
-#include "celt.c"
-#include <math.h>
 
 #if defined(OPUS_X86_MAY_HAVE_SSE) || defined(OPUS_X86_MAY_HAVE_SSE2) || defined(OPUS_X86_MAY_HAVE_SSE4_1)
 # if defined(OPUS_X86_MAY_HAVE_SSE)
@@ -75,6 +70,12 @@
 # include "arm/arm_celt_map.c"
 #endif
 
+#include "pitch.c"     // Note: It could use celt_inner_prod_sse
+#include "celt_lpc.c"
+#include "celt.c"
+#include <math.h>
+#include "vq.c"                // Note: It could use celt_inner_prod_sse
+
 #define MAX_SIZE 100
 
 int ret=0;
`

**Comment by snorkellingcactus** [comment] 2017-01-26 02:32
patch working for me: [https://gist.github.com/snorkellingcactus/c2d2209822bbdb4038c797232b127de1](https://gist.github.com/snorkellingcactus/c2d2209822bbdb4038c797232b127de1)

build log: [https://gist.github.com/snorkellingcactus/c4a629cd6c34c979c0696bdacdb8b2a7](https://gist.github.com/snorkellingcactus/c4a629cd6c34c979c0696bdacdb8b2a7)

**Comment by rillian** [comment] 2017-01-27 04:00
I can reproduce by disabling the `OPUS_CHECK_INTRINSICS([SSE2],...)` call around configure.ac line 559. The tests just assume SSE2 is available.

I worry that your patch is just disabling the tests, rather than fixing the macros to use the right variant on your system.

Which gcc is this that doesn't support anything past SSE? The other side of our C89 compatibility commitment, I guess. :)

**Comment by snorkellingcactus** [comment] 2017-01-27 06:56
The compiler supports sse and all typical stuff. But i'm using icecc for distributed compilation so i can't use -march=native directly. Instead i set the explicit C[XX]FLAGS that the compiler sends to the preprocessor when i pass -march=native. Because of this you can see some -mno-sseN and a bunch of C[XX]FLAGS.

The compiler is GCC 5.4.0.

I build opus on an Intel Celeron which have sse only. ¿isn't celt_inner_prod_sse the right expansion for it?.

I can try to compile it without icecc or custom C[XX]FLAGS and see if i can reproduce the error.

Thanks.

**Comment by jmvalin** [comment] 2017-05-30 18:30
I think it should work fine in master now, since this fix landed: https://git.xiph.org/?p=opus.git;a=commit;h=4507637c
Can you confirm it fixes the issue you're reporting?

**Comment by rillian** [comment] 2017-06-06 20:26
I repeated the reproduction test and the issue is resolved for me. Feel free to reopen if the there are still issues for your setup.

**Closed by rillian** 2017-06-06 20:26 UTC

**Comment by snorkellingcactus** [comment] 2017-08-21 14:28
Looks like it's solved. Thanks!
